#!/usr/bin/env bash

# entry script to launch the service

PROGRAM_PATH=/usr/local/inkywall
VENV_PATH="$PROGRAM_PATH/venv_inkywall"

source "$VENV_PATH/bin/activate"

export PROJECT_DIR="$PROGRAM_PATH"
export SRC_DIR="$PROGRAM_PATH/src"

python -u "$(realpath $PROGRAM_PATH/src/inkywall.py)" "$@"

deactivate
